
// Auto-generated by stably-browser run-test — connects to daemon browser via CDP.
const { defineConfig } = require('@playwright/test');

const userConfigModule = require('/workspace/cmshlvqxq0000i60a141638vu/cypress/e2e/playwright.config.ts');
const userConfig = userConfigModule.default || userConfigModule;

const userProjects = userConfig.projects || [];

// Pass the user's viewport to the CDP fixtures via env var so they can apply it
// to the reused daemon context (which was created with viewport: null).
// Resolution order: selected project's viewport > top-level use.viewport > first project's viewport.
const selectedProject = process.env.__PLAYWRIGHT_CLI_PROJECT__;
const matchedProject = selectedProject
  ? userProjects.find(p => p.name === selectedProject)
  : null;
const userViewport = matchedProject?.use?.viewport
  || userConfig.use?.viewport
  || userProjects[0]?.use?.viewport;
if (userViewport && userViewport.width && userViewport.height) {
  process.env.PLAYWRIGHT_CLI_VIEWPORT = userViewport.width + ',' + userViewport.height;
}

module.exports = defineConfig({
  ...userConfig,
  // Single worker, no retries — for interactive debugging with persistent state
  retries: 0,
  workers: 1,
  // Override reporter to prevent third-party reporters (e.g. @stablyai/reporter)
  // from causing non-zero exit codes due to auth failures
  reporter: [['list']],
  use: {
    ...(userConfig.use || {}),
    video: 'off',
  },
  projects: [
    // Catch-all project for tests that don't belong to a specific project
    { name: 'stably-internal-all-tests-project', testMatch: '**/*' },
    ...userProjects,
  ],
});
