window.esdocSearchIndex = [
  [
    "wavesurfer.js/src/drawer.canvasentry.js~canvasentry",
    "class/src/drawer.canvasentry.js~CanvasEntry.html",
    "<span>CanvasEntry</span> <span class=\"search-result-import-path\">wavesurfer.js/src/drawer.canvasentry.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/cursor.js~cursorplugin",
    "class/src/plugin/cursor.js~CursorPlugin.html",
    "<span>CursorPlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/cursor.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/drawer.js~drawer",
    "class/src/drawer.js~Drawer.html",
    "<span>Drawer</span> <span class=\"search-result-import-path\">wavesurfer.js/src/drawer.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/elan.js~elanplugin",
    "class/src/plugin/elan.js~ElanPlugin.html",
    "<span>ElanPlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/elan.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/html-init.js~init",
    "class/src/html-init.js~Init.html",
    "<span>Init</span> <span class=\"search-result-import-path\">wavesurfer.js/src/html-init.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/mediaelement.js~mediaelement",
    "class/src/mediaelement.js~MediaElement.html",
    "<span>MediaElement</span> <span class=\"search-result-import-path\">wavesurfer.js/src/mediaelement.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/mediasession.js~mediasessionplugin",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html",
    "<span>MediaSessionPlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/mediasession.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/microphone.js~microphoneplugin",
    "class/src/plugin/microphone.js~MicrophonePlugin.html",
    "<span>MicrophonePlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/microphone.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/minimap.js~minimapplugin",
    "class/src/plugin/minimap.js~MinimapPlugin.html",
    "<span>MinimapPlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/minimap.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/drawer.multicanvas.js~multicanvas",
    "class/src/drawer.multicanvas.js~MultiCanvas.html",
    "<span>MultiCanvas</span> <span class=\"search-result-import-path\">wavesurfer.js/src/drawer.multicanvas.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/util/observer.js~observer",
    "class/src/util/observer.js~Observer.html",
    "<span>Observer</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/observer.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/peakcache.js~peakcache",
    "class/src/peakcache.js~PeakCache.html",
    "<span>PeakCache</span> <span class=\"search-result-import-path\">wavesurfer.js/src/peakcache.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/wavesurfer.js~pluginclass",
    "class/src/wavesurfer.js~PluginClass.html",
    "<span>PluginClass</span> <span class=\"search-result-import-path\">wavesurfer.js/src/wavesurfer.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/regions.js~regionsplugin",
    "class/src/plugin/regions.js~RegionsPlugin.html",
    "<span>RegionsPlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/regions.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/spectrogram.js~spectrogramplugin",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html",
    "<span>SpectrogramPlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/spectrogram.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/plugin/timeline.js~timelineplugin",
    "class/src/plugin/timeline.js~TimelinePlugin.html",
    "<span>TimelinePlugin</span> <span class=\"search-result-import-path\">wavesurfer.js/src/plugin/timeline.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/wavesurfer.js~wavesurfer",
    "class/src/wavesurfer.js~WaveSurfer.html",
    "<span>WaveSurfer</span> <span class=\"search-result-import-path\">wavesurfer.js/src/wavesurfer.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/webaudio.js~webaudio",
    "class/src/webaudio.js~WebAudio.html",
    "<span>WebAudio</span> <span class=\"search-result-import-path\">wavesurfer.js/src/webaudio.js</span>",
    "class"
  ],
  [
    "wavesurfer.js/src/util/ajax.js~ajax",
    "function/index.html#static-function-ajax",
    "<span>ajax</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/ajax.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/extend.js~extend",
    "function/index.html#static-function-extend",
    "<span>extend</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/extend.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/fetch.js~fetchfile",
    "function/index.html#static-function-fetchFile",
    "<span>fetchFile</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/fetch.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/frame.js~frame",
    "function/index.html#static-function-frame",
    "<span>frame</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/frame.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/get-id.js~getid",
    "function/index.html#static-function-getId",
    "<span>getId</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/get-id.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/max.js~max",
    "function/index.html#static-function-max",
    "<span>max</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/max.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/min.js~min",
    "function/index.html#static-function-min",
    "<span>min</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/min.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/prevent-click.js~preventclick",
    "function/index.html#static-function-preventClick",
    "<span>preventClick</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/prevent-click.js</span>",
    "function"
  ],
  [
    "wavesurfer.js/src/util/style.js~style",
    "function/index.html#static-function-style",
    "<span>style</span> <span class=\"search-result-import-path\">wavesurfer.js/src/util/style.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/drawer.canvasentry.js",
    "file/src/drawer.canvasentry.js.html",
    "src/drawer.canvasentry.js",
    "file"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#clearwave",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-clearWave",
    "src/drawer.canvasentry.js~CanvasEntry#clearWave",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#constructor",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-constructor-constructor",
    "src/drawer.canvasentry.js~CanvasEntry#constructor",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#destroy",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-destroy",
    "src/drawer.canvasentry.js~CanvasEntry#destroy",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#drawlines",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-drawLines",
    "src/drawer.canvasentry.js~CanvasEntry#drawLines",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#fillrects",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-fillRects",
    "src/drawer.canvasentry.js~CanvasEntry#fillRects",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#getimage",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-getImage",
    "src/drawer.canvasentry.js~CanvasEntry#getImage",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#id",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-member-id",
    "src/drawer.canvasentry.js~CanvasEntry#id",
    "member"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#initprogress",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-initProgress",
    "src/drawer.canvasentry.js~CanvasEntry#initProgress",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#initwave",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-initWave",
    "src/drawer.canvasentry.js~CanvasEntry#initWave",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#progress",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-member-progress",
    "src/drawer.canvasentry.js~CanvasEntry#progress",
    "member"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#progressctx",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-member-progressCtx",
    "src/drawer.canvasentry.js~CanvasEntry#progressCtx",
    "member"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#setfillstyles",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-setFillStyles",
    "src/drawer.canvasentry.js~CanvasEntry#setFillStyles",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#updatedimensions",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-method-updateDimensions",
    "src/drawer.canvasentry.js~CanvasEntry#updateDimensions",
    "method"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#wave",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-member-wave",
    "src/drawer.canvasentry.js~CanvasEntry#wave",
    "member"
  ],
  [
    "src/drawer.canvasentry.js~canvasentry#wavectx",
    "class/src/drawer.canvasentry.js~CanvasEntry.html#instance-member-waveCtx",
    "src/drawer.canvasentry.js~CanvasEntry#waveCtx",
    "member"
  ],
  [
    "src/drawer.js",
    "file/src/drawer.js.html",
    "src/drawer.js",
    "file"
  ],
  [
    "src/drawer.js~drawer#clearwave",
    "class/src/drawer.js~Drawer.html#instance-method-clearWave",
    "src/drawer.js~Drawer#clearWave",
    "method"
  ],
  [
    "src/drawer.js~drawer#constructor",
    "class/src/drawer.js~Drawer.html#instance-constructor-constructor",
    "src/drawer.js~Drawer#constructor",
    "method"
  ],
  [
    "src/drawer.js~drawer#createwrapper",
    "class/src/drawer.js~Drawer.html#instance-method-createWrapper",
    "src/drawer.js~Drawer#createWrapper",
    "method"
  ],
  [
    "src/drawer.js~drawer#destroy",
    "class/src/drawer.js~Drawer.html#instance-method-destroy",
    "src/drawer.js~Drawer#destroy",
    "method"
  ],
  [
    "src/drawer.js~drawer#drawbars",
    "class/src/drawer.js~Drawer.html#instance-method-drawBars",
    "src/drawer.js~Drawer#drawBars",
    "method"
  ],
  [
    "src/drawer.js~drawer#drawpeaks",
    "class/src/drawer.js~Drawer.html#instance-method-drawPeaks",
    "src/drawer.js~Drawer#drawPeaks",
    "method"
  ],
  [
    "src/drawer.js~drawer#drawwave",
    "class/src/drawer.js~Drawer.html#instance-method-drawWave",
    "src/drawer.js~Drawer#drawWave",
    "method"
  ],
  [
    "src/drawer.js~drawer#getscrollx",
    "class/src/drawer.js~Drawer.html#instance-method-getScrollX",
    "src/drawer.js~Drawer#getScrollX",
    "method"
  ],
  [
    "src/drawer.js~drawer#getwidth",
    "class/src/drawer.js~Drawer.html#instance-method-getWidth",
    "src/drawer.js~Drawer#getWidth",
    "method"
  ],
  [
    "src/drawer.js~drawer#handleevent",
    "class/src/drawer.js~Drawer.html#instance-method-handleEvent",
    "src/drawer.js~Drawer#handleEvent",
    "method"
  ],
  [
    "src/drawer.js~drawer#height",
    "class/src/drawer.js~Drawer.html#instance-member-height",
    "src/drawer.js~Drawer#height",
    "member"
  ],
  [
    "src/drawer.js~drawer#progress",
    "class/src/drawer.js~Drawer.html#instance-method-progress",
    "src/drawer.js~Drawer#progress",
    "method"
  ],
  [
    "src/drawer.js~drawer#recenter",
    "class/src/drawer.js~Drawer.html#instance-method-recenter",
    "src/drawer.js~Drawer#recenter",
    "method"
  ],
  [
    "src/drawer.js~drawer#recenteronposition",
    "class/src/drawer.js~Drawer.html#instance-method-recenterOnPosition",
    "src/drawer.js~Drawer#recenterOnPosition",
    "method"
  ],
  [
    "src/drawer.js~drawer#resetscroll",
    "class/src/drawer.js~Drawer.html#instance-method-resetScroll",
    "src/drawer.js~Drawer#resetScroll",
    "method"
  ],
  [
    "src/drawer.js~drawer#setheight",
    "class/src/drawer.js~Drawer.html#instance-method-setHeight",
    "src/drawer.js~Drawer#setHeight",
    "method"
  ],
  [
    "src/drawer.js~drawer#setwidth",
    "class/src/drawer.js~Drawer.html#instance-method-setWidth",
    "src/drawer.js~Drawer#setWidth",
    "method"
  ],
  [
    "src/drawer.js~drawer#style",
    "class/src/drawer.js~Drawer.html#instance-method-style",
    "src/drawer.js~Drawer#style",
    "method"
  ],
  [
    "src/drawer.js~drawer#updatecursor",
    "class/src/drawer.js~Drawer.html#instance-method-updateCursor",
    "src/drawer.js~Drawer#updateCursor",
    "method"
  ],
  [
    "src/drawer.js~drawer#updateprogress",
    "class/src/drawer.js~Drawer.html#instance-method-updateProgress",
    "src/drawer.js~Drawer#updateProgress",
    "method"
  ],
  [
    "src/drawer.js~drawer#updatesize",
    "class/src/drawer.js~Drawer.html#instance-method-updateSize",
    "src/drawer.js~Drawer#updateSize",
    "method"
  ],
  [
    "src/drawer.js~drawer#width",
    "class/src/drawer.js~Drawer.html#instance-member-width",
    "src/drawer.js~Drawer#width",
    "member"
  ],
  [
    "src/drawer.js~drawer#wrapper",
    "class/src/drawer.js~Drawer.html#instance-member-wrapper",
    "src/drawer.js~Drawer#wrapper",
    "member"
  ],
  [
    "src/drawer.multicanvas.js",
    "file/src/drawer.multicanvas.js.html",
    "src/drawer.multicanvas.js",
    "file"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#clearwave",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-clearWave",
    "src/drawer.multicanvas.js~MultiCanvas#clearWave",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#constructor",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-constructor-constructor",
    "src/drawer.multicanvas.js~MultiCanvas#constructor",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#drawbars",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-drawBars",
    "src/drawer.multicanvas.js~MultiCanvas#drawBars",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#drawwave",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-drawWave",
    "src/drawer.multicanvas.js~MultiCanvas#drawWave",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#fillrect",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-fillRect",
    "src/drawer.multicanvas.js~MultiCanvas#fillRect",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#getimage",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-getImage",
    "src/drawer.multicanvas.js~MultiCanvas#getImage",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#hasprogresscanvas",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-member-hasProgressCanvas",
    "src/drawer.multicanvas.js~MultiCanvas#hasProgressCanvas",
    "member"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#init",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-init",
    "src/drawer.multicanvas.js~MultiCanvas#init",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#overlap",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-member-overlap",
    "src/drawer.multicanvas.js~MultiCanvas#overlap",
    "member"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#updatecursor",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-updateCursor",
    "src/drawer.multicanvas.js~MultiCanvas#updateCursor",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#updateprogress",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-updateProgress",
    "src/drawer.multicanvas.js~MultiCanvas#updateProgress",
    "method"
  ],
  [
    "src/drawer.multicanvas.js~multicanvas#updatesize",
    "class/src/drawer.multicanvas.js~MultiCanvas.html#instance-method-updateSize",
    "src/drawer.multicanvas.js~MultiCanvas#updateSize",
    "method"
  ],
  [
    "src/html-init.js",
    "file/src/html-init.js.html",
    "src/html-init.js",
    "file"
  ],
  [
    "src/html-init.js~init#constructor",
    "class/src/html-init.js~Init.html#instance-constructor-constructor",
    "src/html-init.js~Init#constructor",
    "method"
  ],
  [
    "src/html-init.js~init#containers",
    "class/src/html-init.js~Init.html#instance-member-containers",
    "src/html-init.js~Init#containers",
    "member"
  ],
  [
    "src/html-init.js~init#initallels",
    "class/src/html-init.js~Init.html#instance-method-initAllEls",
    "src/html-init.js~Init#initAllEls",
    "method"
  ],
  [
    "src/html-init.js~init#initel",
    "class/src/html-init.js~Init.html#instance-method-initEl",
    "src/html-init.js~Init#initEl",
    "method"
  ],
  [
    "src/html-init.js~init#instances",
    "class/src/html-init.js~Init.html#instance-member-instances",
    "src/html-init.js~Init#instances",
    "member"
  ],
  [
    "src/html-init.js~initparams",
    "typedef/index.html#static-typedef-InitParams",
    "src/html-init.js~InitParams",
    "typedef"
  ],
  [
    "src/mediaelement.js",
    "file/src/mediaelement.js.html",
    "src/mediaelement.js",
    "file"
  ],
  [
    "src/mediaelement.js~mediaelement#constructor",
    "class/src/mediaelement.js~MediaElement.html#instance-constructor-constructor",
    "src/mediaelement.js~MediaElement#constructor",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#destroy",
    "class/src/mediaelement.js~MediaElement.html#instance-method-destroy",
    "src/mediaelement.js~MediaElement#destroy",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#getcurrenttime",
    "class/src/mediaelement.js~MediaElement.html#instance-method-getCurrentTime",
    "src/mediaelement.js~MediaElement#getCurrentTime",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#getduration",
    "class/src/mediaelement.js~MediaElement.html#instance-method-getDuration",
    "src/mediaelement.js~MediaElement#getDuration",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#getpeaks",
    "class/src/mediaelement.js~MediaElement.html#instance-method-getPeaks",
    "src/mediaelement.js~MediaElement#getPeaks",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#getplaybackrate",
    "class/src/mediaelement.js~MediaElement.html#instance-method-getPlaybackRate",
    "src/mediaelement.js~MediaElement#getPlaybackRate",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#getplayedpercents",
    "class/src/mediaelement.js~MediaElement.html#instance-method-getPlayedPercents",
    "src/mediaelement.js~MediaElement#getPlayedPercents",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#getvolume",
    "class/src/mediaelement.js~MediaElement.html#instance-method-getVolume",
    "src/mediaelement.js~MediaElement#getVolume",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#init",
    "class/src/mediaelement.js~MediaElement.html#instance-method-init",
    "src/mediaelement.js~MediaElement#init",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#ispaused",
    "class/src/mediaelement.js~MediaElement.html#instance-method-isPaused",
    "src/mediaelement.js~MediaElement#isPaused",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#load",
    "class/src/mediaelement.js~MediaElement.html#instance-method-load",
    "src/mediaelement.js~MediaElement#load",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#loadelt",
    "class/src/mediaelement.js~MediaElement.html#instance-method-loadElt",
    "src/mediaelement.js~MediaElement#loadElt",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#pause",
    "class/src/mediaelement.js~MediaElement.html#instance-method-pause",
    "src/mediaelement.js~MediaElement#pause",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#play",
    "class/src/mediaelement.js~MediaElement.html#instance-method-play",
    "src/mediaelement.js~MediaElement#play",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#seekto",
    "class/src/mediaelement.js~MediaElement.html#instance-method-seekTo",
    "src/mediaelement.js~MediaElement#seekTo",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#setplaybackrate",
    "class/src/mediaelement.js~MediaElement.html#instance-method-setPlaybackRate",
    "src/mediaelement.js~MediaElement#setPlaybackRate",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#setsinkid",
    "class/src/mediaelement.js~MediaElement.html#instance-method-setSinkId",
    "src/mediaelement.js~MediaElement#setSinkId",
    "method"
  ],
  [
    "src/mediaelement.js~mediaelement#setvolume",
    "class/src/mediaelement.js~MediaElement.html#instance-method-setVolume",
    "src/mediaelement.js~MediaElement#setVolume",
    "method"
  ],
  [
    "src/peakcache.js",
    "file/src/peakcache.js.html",
    "src/peakcache.js",
    "file"
  ],
  [
    "src/peakcache.js~peakcache#addrangetopeakcache",
    "class/src/peakcache.js~PeakCache.html#instance-method-addRangeToPeakCache",
    "src/peakcache.js~PeakCache#addRangeToPeakCache",
    "method"
  ],
  [
    "src/peakcache.js~peakcache#clearpeakcache",
    "class/src/peakcache.js~PeakCache.html#instance-method-clearPeakCache",
    "src/peakcache.js~PeakCache#clearPeakCache",
    "method"
  ],
  [
    "src/peakcache.js~peakcache#constructor",
    "class/src/peakcache.js~PeakCache.html#instance-constructor-constructor",
    "src/peakcache.js~PeakCache#constructor",
    "method"
  ],
  [
    "src/peakcache.js~peakcache#getcacheranges",
    "class/src/peakcache.js~PeakCache.html#instance-method-getCacheRanges",
    "src/peakcache.js~PeakCache#getCacheRanges",
    "method"
  ],
  [
    "src/plugin/cursor.js",
    "file/src/plugin/cursor.js.html",
    "src/plugin/cursor.js",
    "file"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#constructor",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-constructor-constructor",
    "src/plugin/cursor.js~CursorPlugin#constructor",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#cursor",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-member-cursor",
    "src/plugin/cursor.js~CursorPlugin#cursor",
    "member"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#defaultparams",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-member-defaultParams",
    "src/plugin/cursor.js~CursorPlugin#defaultParams",
    "member"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#destroy",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-method-destroy",
    "src/plugin/cursor.js~CursorPlugin#destroy",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#displaytime",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-member-displayTime",
    "src/plugin/cursor.js~CursorPlugin#displayTime",
    "member"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#formattime",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-method-formatTime",
    "src/plugin/cursor.js~CursorPlugin#formatTime",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#hidecursor",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-method-hideCursor",
    "src/plugin/cursor.js~CursorPlugin#hideCursor",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#init",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-method-init",
    "src/plugin/cursor.js~CursorPlugin#init",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#showcursor",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-method-showCursor",
    "src/plugin/cursor.js~CursorPlugin#showCursor",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#showtime",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-member-showTime",
    "src/plugin/cursor.js~CursorPlugin#showTime",
    "member"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#updatecursorposition",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-method-updateCursorPosition",
    "src/plugin/cursor.js~CursorPlugin#updateCursorPosition",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorplugin#wrapper",
    "class/src/plugin/cursor.js~CursorPlugin.html#instance-member-wrapper",
    "src/plugin/cursor.js~CursorPlugin#wrapper",
    "member"
  ],
  [
    "src/plugin/cursor.js~cursorplugin.create",
    "class/src/plugin/cursor.js~CursorPlugin.html#static-method-create",
    "src/plugin/cursor.js~CursorPlugin.create",
    "method"
  ],
  [
    "src/plugin/cursor.js~cursorpluginparams",
    "typedef/index.html#static-typedef-CursorPluginParams",
    "src/plugin/cursor.js~CursorPluginParams",
    "typedef"
  ],
  [
    "src/plugin/elan.js",
    "file/src/plugin/elan.js.html",
    "src/plugin/elan.js",
    "file"
  ],
  [
    "src/plugin/elan.js~elanplugin#types",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-member-Types",
    "src/plugin/elan.js~ElanPlugin#Types",
    "member"
  ],
  [
    "src/plugin/elan.js~elanplugin#bindclick",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-bindClick",
    "src/plugin/elan.js~ElanPlugin#bindClick",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#constructor",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-constructor-constructor",
    "src/plugin/elan.js~ElanPlugin#constructor",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#container",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-member-container",
    "src/plugin/elan.js~ElanPlugin#container",
    "member"
  ],
  [
    "src/plugin/elan.js~elanplugin#data",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-member-data",
    "src/plugin/elan.js~ElanPlugin#data",
    "member"
  ],
  [
    "src/plugin/elan.js~elanplugin#destroy",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-destroy",
    "src/plugin/elan.js~ElanPlugin#destroy",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#getannotationnode",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-getAnnotationNode",
    "src/plugin/elan.js~ElanPlugin#getAnnotationNode",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#getrenderedannotation",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-getRenderedAnnotation",
    "src/plugin/elan.js~ElanPlugin#getRenderedAnnotation",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#init",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-init",
    "src/plugin/elan.js~ElanPlugin#init",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#load",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-load",
    "src/plugin/elan.js~ElanPlugin#load",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#loadxml",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-loadXML",
    "src/plugin/elan.js~ElanPlugin#loadXML",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#params",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-member-params",
    "src/plugin/elan.js~ElanPlugin#params",
    "member"
  ],
  [
    "src/plugin/elan.js~elanplugin#parseelan",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-parseElan",
    "src/plugin/elan.js~ElanPlugin#parseElan",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#render",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-method-render",
    "src/plugin/elan.js~ElanPlugin#render",
    "method"
  ],
  [
    "src/plugin/elan.js~elanplugin#renderedalignable",
    "class/src/plugin/elan.js~ElanPlugin.html#instance-member-renderedAlignable",
    "src/plugin/elan.js~ElanPlugin#renderedAlignable",
    "member"
  ],
  [
    "src/plugin/elan.js~elanplugin.create",
    "class/src/plugin/elan.js~ElanPlugin.html#static-method-create",
    "src/plugin/elan.js~ElanPlugin.create",
    "method"
  ],
  [
    "src/plugin/elan.js~elanpluginparams",
    "typedef/index.html#static-typedef-ElanPluginParams",
    "src/plugin/elan.js~ElanPluginParams",
    "typedef"
  ],
  [
    "src/plugin/mediasession.js",
    "file/src/plugin/mediasession.js.html",
    "src/plugin/mediasession.js",
    "file"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#constructor",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-constructor-constructor",
    "src/plugin/mediasession.js~MediaSessionPlugin#constructor",
    "method"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#destroy",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-method-destroy",
    "src/plugin/mediasession.js~MediaSessionPlugin#destroy",
    "method"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#init",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-method-init",
    "src/plugin/mediasession.js~MediaSessionPlugin#init",
    "method"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#metadata",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-member-metadata",
    "src/plugin/mediasession.js~MediaSessionPlugin#metadata",
    "member"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#params",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-member-params",
    "src/plugin/mediasession.js~MediaSessionPlugin#params",
    "member"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#update",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-method-update",
    "src/plugin/mediasession.js~MediaSessionPlugin#update",
    "method"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin#wavesurfer",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#instance-member-wavesurfer",
    "src/plugin/mediasession.js~MediaSessionPlugin#wavesurfer",
    "member"
  ],
  [
    "src/plugin/mediasession.js~mediasessionplugin.create",
    "class/src/plugin/mediasession.js~MediaSessionPlugin.html#static-method-create",
    "src/plugin/mediasession.js~MediaSessionPlugin.create",
    "method"
  ],
  [
    "src/plugin/mediasession.js~mediasessionpluginparams",
    "typedef/index.html#static-typedef-MediaSessionPluginParams",
    "src/plugin/mediasession.js~MediaSessionPluginParams",
    "typedef"
  ],
  [
    "src/plugin/microphone.js",
    "file/src/plugin/microphone.js.html",
    "src/plugin/microphone.js",
    "file"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#active",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-active",
    "src/plugin/microphone.js~MicrophonePlugin#active",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#browser",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-browser",
    "src/plugin/microphone.js~MicrophonePlugin#browser",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#buffersize",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-bufferSize",
    "src/plugin/microphone.js~MicrophonePlugin#bufferSize",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#connect",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-connect",
    "src/plugin/microphone.js~MicrophonePlugin#connect",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#constraints",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-constraints",
    "src/plugin/microphone.js~MicrophonePlugin#constraints",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#constructor",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-constructor-constructor",
    "src/plugin/microphone.js~MicrophonePlugin#constructor",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#destroy",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-destroy",
    "src/plugin/microphone.js~MicrophonePlugin#destroy",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#detectbrowser",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-detectBrowser",
    "src/plugin/microphone.js~MicrophonePlugin#detectBrowser",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#deviceerror",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-deviceError",
    "src/plugin/microphone.js~MicrophonePlugin#deviceError",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#disconnect",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-disconnect",
    "src/plugin/microphone.js~MicrophonePlugin#disconnect",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#extractversion",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-extractVersion",
    "src/plugin/microphone.js~MicrophonePlugin#extractVersion",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#gotstream",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-gotStream",
    "src/plugin/microphone.js~MicrophonePlugin#gotStream",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#init",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-init",
    "src/plugin/microphone.js~MicrophonePlugin#init",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#levelchecker",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-levelChecker",
    "src/plugin/microphone.js~MicrophonePlugin#levelChecker",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#localaudiobuffer",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-localAudioBuffer",
    "src/plugin/microphone.js~MicrophonePlugin#localAudioBuffer",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#mediastreamsource",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-mediaStreamSource",
    "src/plugin/microphone.js~MicrophonePlugin#mediaStreamSource",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#miccontext",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-micContext",
    "src/plugin/microphone.js~MicrophonePlugin#micContext",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#numberofinputchannels",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-numberOfInputChannels",
    "src/plugin/microphone.js~MicrophonePlugin#numberOfInputChannels",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#numberofoutputchannels",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-numberOfOutputChannels",
    "src/plugin/microphone.js~MicrophonePlugin#numberOfOutputChannels",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#params",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-params",
    "src/plugin/microphone.js~MicrophonePlugin#params",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#pause",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-pause",
    "src/plugin/microphone.js~MicrophonePlugin#pause",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#paused",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-paused",
    "src/plugin/microphone.js~MicrophonePlugin#paused",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#play",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-play",
    "src/plugin/microphone.js~MicrophonePlugin#play",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#reloadbuffer",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-reloadBuffer",
    "src/plugin/microphone.js~MicrophonePlugin#reloadBuffer",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#reloadbufferfunction",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-reloadBufferFunction",
    "src/plugin/microphone.js~MicrophonePlugin#reloadBufferFunction",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#start",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-start",
    "src/plugin/microphone.js~MicrophonePlugin#start",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#stop",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-stop",
    "src/plugin/microphone.js~MicrophonePlugin#stop",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#stopdevice",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-stopDevice",
    "src/plugin/microphone.js~MicrophonePlugin#stopDevice",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#stream",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-stream",
    "src/plugin/microphone.js~MicrophonePlugin#stream",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#toggleplay",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-method-togglePlay",
    "src/plugin/microphone.js~MicrophonePlugin#togglePlay",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin#wavesurfer",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#instance-member-wavesurfer",
    "src/plugin/microphone.js~MicrophonePlugin#wavesurfer",
    "member"
  ],
  [
    "src/plugin/microphone.js~microphoneplugin.create",
    "class/src/plugin/microphone.js~MicrophonePlugin.html#static-method-create",
    "src/plugin/microphone.js~MicrophonePlugin.create",
    "method"
  ],
  [
    "src/plugin/microphone.js~microphonepluginparams",
    "typedef/index.html#static-typedef-MicrophonePluginParams",
    "src/plugin/microphone.js~MicrophonePluginParams",
    "typedef"
  ],
  [
    "src/plugin/minimap.js",
    "file/src/plugin/minimap.js.html",
    "src/plugin/minimap.js",
    "file"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#bindminimapevents",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-bindMinimapEvents",
    "src/plugin/minimap.js~MinimapPlugin#bindMinimapEvents",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#bindwavesurferevents",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-bindWavesurferEvents",
    "src/plugin/minimap.js~MinimapPlugin#bindWavesurferEvents",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#constructor",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-constructor-constructor",
    "src/plugin/minimap.js~MinimapPlugin#constructor",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#createelements",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-createElements",
    "src/plugin/minimap.js~MinimapPlugin#createElements",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#destroy",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-destroy",
    "src/plugin/minimap.js~MinimapPlugin#destroy",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#draggingoverview",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-draggingOverview",
    "src/plugin/minimap.js~MinimapPlugin#draggingOverview",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#drawer",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-drawer",
    "src/plugin/minimap.js~MinimapPlugin#drawer",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#init",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-init",
    "src/plugin/minimap.js~MinimapPlugin#init",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#moveoverviewregion",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-moveOverviewRegion",
    "src/plugin/minimap.js~MinimapPlugin#moveOverviewRegion",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#overviewposition",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-overviewPosition",
    "src/plugin/minimap.js~MinimapPlugin#overviewPosition",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#overviewregion",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-overviewRegion",
    "src/plugin/minimap.js~MinimapPlugin#overviewRegion",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#overviewwidth",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-overviewWidth",
    "src/plugin/minimap.js~MinimapPlugin#overviewWidth",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#params",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-params",
    "src/plugin/minimap.js~MinimapPlugin#params",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#ratio",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-ratio",
    "src/plugin/minimap.js~MinimapPlugin#ratio",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#regions",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-regions",
    "src/plugin/minimap.js~MinimapPlugin#regions",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#render",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-render",
    "src/plugin/minimap.js~MinimapPlugin#render",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#renderevent",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-renderEvent",
    "src/plugin/minimap.js~MinimapPlugin#renderEvent",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#renderregions",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-method-renderRegions",
    "src/plugin/minimap.js~MinimapPlugin#renderRegions",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#util",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-util",
    "src/plugin/minimap.js~MinimapPlugin#util",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#waveshowedwidth",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-waveShowedWidth",
    "src/plugin/minimap.js~MinimapPlugin#waveShowedWidth",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#wavewidth",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-waveWidth",
    "src/plugin/minimap.js~MinimapPlugin#waveWidth",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin#wavesurfer",
    "class/src/plugin/minimap.js~MinimapPlugin.html#instance-member-wavesurfer",
    "src/plugin/minimap.js~MinimapPlugin#wavesurfer",
    "member"
  ],
  [
    "src/plugin/minimap.js~minimapplugin.create",
    "class/src/plugin/minimap.js~MinimapPlugin.html#static-method-create",
    "src/plugin/minimap.js~MinimapPlugin.create",
    "method"
  ],
  [
    "src/plugin/minimap.js~minimappluginparams",
    "typedef/index.html#static-typedef-MinimapPluginParams",
    "src/plugin/minimap.js~MinimapPluginParams",
    "typedef"
  ],
  [
    "src/plugin/regions.js",
    "file/src/plugin/regions.js.html",
    "src/plugin/regions.js",
    "file"
  ],
  [
    "src/plugin/regions.js~regionparams",
    "typedef/index.html#static-typedef-RegionParams",
    "src/plugin/regions.js~RegionParams",
    "typedef"
  ],
  [
    "src/plugin/regions.js~regionsplugin#add",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-add",
    "src/plugin/regions.js~RegionsPlugin#add",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#clear",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-clear",
    "src/plugin/regions.js~RegionsPlugin#clear",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#constructor",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-constructor-constructor",
    "src/plugin/regions.js~RegionsPlugin#constructor",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#destroy",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-destroy",
    "src/plugin/regions.js~RegionsPlugin#destroy",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#disabledragselection",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-disableDragSelection",
    "src/plugin/regions.js~RegionsPlugin#disableDragSelection",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#enabledragselection",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-enableDragSelection",
    "src/plugin/regions.js~RegionsPlugin#enableDragSelection",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#getcurrentregion",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-getCurrentRegion",
    "src/plugin/regions.js~RegionsPlugin#getCurrentRegion",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#getregionsnaptogridvalue",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-getRegionSnapToGridValue",
    "src/plugin/regions.js~RegionsPlugin#getRegionSnapToGridValue",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#init",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-method-init",
    "src/plugin/regions.js~RegionsPlugin#init",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin#list",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-member-list",
    "src/plugin/regions.js~RegionsPlugin#list",
    "member"
  ],
  [
    "src/plugin/regions.js~regionsplugin#params",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-member-params",
    "src/plugin/regions.js~RegionsPlugin#params",
    "member"
  ],
  [
    "src/plugin/regions.js~regionsplugin#util",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-member-util",
    "src/plugin/regions.js~RegionsPlugin#util",
    "member"
  ],
  [
    "src/plugin/regions.js~regionsplugin#wavesurfer",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-member-wavesurfer",
    "src/plugin/regions.js~RegionsPlugin#wavesurfer",
    "member"
  ],
  [
    "src/plugin/regions.js~regionsplugin#wrapper",
    "class/src/plugin/regions.js~RegionsPlugin.html#instance-member-wrapper",
    "src/plugin/regions.js~RegionsPlugin#wrapper",
    "member"
  ],
  [
    "src/plugin/regions.js~regionsplugin.create",
    "class/src/plugin/regions.js~RegionsPlugin.html#static-method-create",
    "src/plugin/regions.js~RegionsPlugin.create",
    "method"
  ],
  [
    "src/plugin/regions.js~regionsplugin.regions",
    "class/src/plugin/regions.js~RegionsPlugin.html#static-member-regions",
    "src/plugin/regions.js~RegionsPlugin.regions",
    "member"
  ],
  [
    "src/plugin/regions.js~regionspluginparams",
    "typedef/index.html#static-typedef-RegionsPluginParams",
    "src/plugin/regions.js~RegionsPluginParams",
    "typedef"
  ],
  [
    "src/plugin/spectrogram.js",
    "file/src/plugin/spectrogram.js.html",
    "src/plugin/spectrogram.js",
    "file"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#alpha",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-alpha",
    "src/plugin/spectrogram.js~SpectrogramPlugin#alpha",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#colormap",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-colorMap",
    "src/plugin/spectrogram.js~SpectrogramPlugin#colorMap",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#constructor",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-constructor-constructor",
    "src/plugin/spectrogram.js~SpectrogramPlugin#constructor",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#container",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-container",
    "src/plugin/spectrogram.js~SpectrogramPlugin#container",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#createcanvas",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-createCanvas",
    "src/plugin/spectrogram.js~SpectrogramPlugin#createCanvas",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#createwrapper",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-createWrapper",
    "src/plugin/spectrogram.js~SpectrogramPlugin#createWrapper",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#destroy",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-destroy",
    "src/plugin/spectrogram.js~SpectrogramPlugin#destroy",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#drawspectrogram",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-drawSpectrogram",
    "src/plugin/spectrogram.js~SpectrogramPlugin#drawSpectrogram",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#fftsamples",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-fftSamples",
    "src/plugin/spectrogram.js~SpectrogramPlugin#fftSamples",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#freqtype",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-freqType",
    "src/plugin/spectrogram.js~SpectrogramPlugin#freqType",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#frequenciesdataurl",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-frequenciesDataUrl",
    "src/plugin/spectrogram.js~SpectrogramPlugin#frequenciesDataUrl",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#getfrequencies",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-getFrequencies",
    "src/plugin/spectrogram.js~SpectrogramPlugin#getFrequencies",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#height",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-height",
    "src/plugin/spectrogram.js~SpectrogramPlugin#height",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#init",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-init",
    "src/plugin/spectrogram.js~SpectrogramPlugin#init",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#loadfrequenciesdata",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-loadFrequenciesData",
    "src/plugin/spectrogram.js~SpectrogramPlugin#loadFrequenciesData",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#loadlabels",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-loadLabels",
    "src/plugin/spectrogram.js~SpectrogramPlugin#loadLabels",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#noverlap",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-noverlap",
    "src/plugin/spectrogram.js~SpectrogramPlugin#noverlap",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#params",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-params",
    "src/plugin/spectrogram.js~SpectrogramPlugin#params",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#pixelratio",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-pixelRatio",
    "src/plugin/spectrogram.js~SpectrogramPlugin#pixelRatio",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#render",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-render",
    "src/plugin/spectrogram.js~SpectrogramPlugin#render",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#resample",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-resample",
    "src/plugin/spectrogram.js~SpectrogramPlugin#resample",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#spectrcc",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-spectrCc",
    "src/plugin/spectrogram.js~SpectrogramPlugin#spectrCc",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#unittype",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-unitType",
    "src/plugin/spectrogram.js~SpectrogramPlugin#unitType",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#updatecanvasstyle",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-updateCanvasStyle",
    "src/plugin/spectrogram.js~SpectrogramPlugin#updateCanvasStyle",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#updatescroll",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-method-updateScroll",
    "src/plugin/spectrogram.js~SpectrogramPlugin#updateScroll",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#util",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-util",
    "src/plugin/spectrogram.js~SpectrogramPlugin#util",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#wavesurfer",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-wavesurfer",
    "src/plugin/spectrogram.js~SpectrogramPlugin#wavesurfer",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#width",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-width",
    "src/plugin/spectrogram.js~SpectrogramPlugin#width",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#windowfunc",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-windowFunc",
    "src/plugin/spectrogram.js~SpectrogramPlugin#windowFunc",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin#wrapper",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#instance-member-wrapper",
    "src/plugin/spectrogram.js~SpectrogramPlugin#wrapper",
    "member"
  ],
  [
    "src/plugin/spectrogram.js~spectrogramplugin.create",
    "class/src/plugin/spectrogram.js~SpectrogramPlugin.html#static-method-create",
    "src/plugin/spectrogram.js~SpectrogramPlugin.create",
    "method"
  ],
  [
    "src/plugin/spectrogram.js~spectrogrampluginparams",
    "typedef/index.html#static-typedef-SpectrogramPluginParams",
    "src/plugin/spectrogram.js~SpectrogramPluginParams",
    "typedef"
  ],
  [
    "src/plugin/timeline.js",
    "file/src/plugin/timeline.js.html",
    "src/plugin/timeline.js",
    "file"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#constructor",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-constructor-constructor",
    "src/plugin/timeline.js~TimelinePlugin#constructor",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#defaultformattimecallback",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-method-defaultFormatTimeCallback",
    "src/plugin/timeline.js~TimelinePlugin#defaultFormatTimeCallback",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#defaultprimarylabelinterval",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-method-defaultPrimaryLabelInterval",
    "src/plugin/timeline.js~TimelinePlugin#defaultPrimaryLabelInterval",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#defaultsecondarylabelinterval",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-method-defaultSecondaryLabelInterval",
    "src/plugin/timeline.js~TimelinePlugin#defaultSecondaryLabelInterval",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#defaulttimeinterval",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-method-defaultTimeInterval",
    "src/plugin/timeline.js~TimelinePlugin#defaultTimeInterval",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#destroy",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-method-destroy",
    "src/plugin/timeline.js~TimelinePlugin#destroy",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#drawer",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-member-drawer",
    "src/plugin/timeline.js~TimelinePlugin#drawer",
    "member"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#init",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-method-init",
    "src/plugin/timeline.js~TimelinePlugin#init",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#maxcanvaselementwidth",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-member-maxCanvasElementWidth",
    "src/plugin/timeline.js~TimelinePlugin#maxCanvasElementWidth",
    "member"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#maxcanvaswidth",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-member-maxCanvasWidth",
    "src/plugin/timeline.js~TimelinePlugin#maxCanvasWidth",
    "member"
  ],
  [
    "src/plugin/timeline.js~timelineplugin#pixelratio",
    "class/src/plugin/timeline.js~TimelinePlugin.html#instance-member-pixelRatio",
    "src/plugin/timeline.js~TimelinePlugin#pixelRatio",
    "member"
  ],
  [
    "src/plugin/timeline.js~timelineplugin.create",
    "class/src/plugin/timeline.js~TimelinePlugin.html#static-method-create",
    "src/plugin/timeline.js~TimelinePlugin.create",
    "method"
  ],
  [
    "src/plugin/timeline.js~timelinepluginparams",
    "typedef/index.html#static-typedef-TimelinePluginParams",
    "src/plugin/timeline.js~TimelinePluginParams",
    "typedef"
  ],
  [
    "src/util/ajax.js",
    "file/src/util/ajax.js.html",
    "src/util/ajax.js",
    "file"
  ],
  [
    "src/util/extend.js",
    "file/src/util/extend.js.html",
    "src/util/extend.js",
    "file"
  ],
  [
    "src/util/fetch.js",
    "file/src/util/fetch.js.html",
    "src/util/fetch.js",
    "file"
  ],
  [
    "src/util/frame.js",
    "file/src/util/frame.js.html",
    "src/util/frame.js",
    "file"
  ],
  [
    "src/util/get-id.js",
    "file/src/util/get-id.js.html",
    "src/util/get-id.js",
    "file"
  ],
  [
    "src/util/index.js",
    "file/src/util/index.js.html",
    "src/util/index.js",
    "file"
  ],
  [
    "src/util/max.js",
    "file/src/util/max.js.html",
    "src/util/max.js",
    "file"
  ],
  [
    "src/util/min.js",
    "file/src/util/min.js.html",
    "src/util/min.js",
    "file"
  ],
  [
    "src/util/observer.js",
    "file/src/util/observer.js.html",
    "src/util/observer.js",
    "file"
  ],
  [
    "src/util/observer.js~listenerdescriptor",
    "typedef/index.html#static-typedef-ListenerDescriptor",
    "src/util/observer.js~ListenerDescriptor",
    "typedef"
  ],
  [
    "src/util/observer.js~observer#constructor",
    "class/src/util/observer.js~Observer.html#instance-constructor-constructor",
    "src/util/observer.js~Observer#constructor",
    "method"
  ],
  [
    "src/util/observer.js~observer#fireevent",
    "class/src/util/observer.js~Observer.html#instance-method-fireEvent",
    "src/util/observer.js~Observer#fireEvent",
    "method"
  ],
  [
    "src/util/observer.js~observer#on",
    "class/src/util/observer.js~Observer.html#instance-method-on",
    "src/util/observer.js~Observer#on",
    "method"
  ],
  [
    "src/util/observer.js~observer#once",
    "class/src/util/observer.js~Observer.html#instance-method-once",
    "src/util/observer.js~Observer#once",
    "method"
  ],
  [
    "src/util/observer.js~observer#un",
    "class/src/util/observer.js~Observer.html#instance-method-un",
    "src/util/observer.js~Observer#un",
    "method"
  ],
  [
    "src/util/observer.js~observer#unall",
    "class/src/util/observer.js~Observer.html#instance-method-unAll",
    "src/util/observer.js~Observer#unAll",
    "method"
  ],
  [
    "src/util/prevent-click.js",
    "file/src/util/prevent-click.js.html",
    "src/util/prevent-click.js",
    "file"
  ],
  [
    "src/util/request-animation-frame.js",
    "file/src/util/request-animation-frame.js.html",
    "src/util/request-animation-frame.js",
    "file"
  ],
  [
    "src/util/style.js",
    "file/src/util/style.js.html",
    "src/util/style.js",
    "file"
  ],
  [
    "src/wavesurfer.js",
    "file/src/wavesurfer.js.html",
    "src/wavesurfer.js",
    "file"
  ],
  [
    "src/wavesurfer.js~audionode",
    "https://developer.mozilla.org/de/docs/Web/API/AudioNode",
    "src/wavesurfer.js~AudioNode",
    "external"
  ],
  [
    "src/wavesurfer.js~blob",
    "https://developer.mozilla.org/en-US/docs/Web/API/Blob",
    "src/wavesurfer.js~Blob",
    "external"
  ],
  [
    "src/wavesurfer.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "src/wavesurfer.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "src/wavesurfer.js~file",
    "https://developer.mozilla.org/en-US/docs/Web/API/File",
    "src/wavesurfer.js~File",
    "external"
  ],
  [
    "src/wavesurfer.js~htmlelement",
    "https://developer.mozilla.org/en/docs/Web/API/HTMLElement",
    "src/wavesurfer.js~HTMLElement",
    "external"
  ],
  [
    "src/wavesurfer.js~mediastreamconstraints",
    "https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints",
    "src/wavesurfer.js~MediaStreamConstraints",
    "external"
  ],
  [
    "src/wavesurfer.js~offlineaudiocontext",
    "https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext",
    "src/wavesurfer.js~OfflineAudioContext",
    "external"
  ],
  [
    "src/wavesurfer.js~pluginclass#constructor",
    "class/src/wavesurfer.js~PluginClass.html#instance-constructor-constructor",
    "src/wavesurfer.js~PluginClass#constructor",
    "method"
  ],
  [
    "src/wavesurfer.js~pluginclass#create",
    "class/src/wavesurfer.js~PluginClass.html#instance-method-create",
    "src/wavesurfer.js~PluginClass#create",
    "method"
  ],
  [
    "src/wavesurfer.js~pluginclass#destroy",
    "class/src/wavesurfer.js~PluginClass.html#instance-method-destroy",
    "src/wavesurfer.js~PluginClass#destroy",
    "method"
  ],
  [
    "src/wavesurfer.js~pluginclass#init",
    "class/src/wavesurfer.js~PluginClass.html#instance-method-init",
    "src/wavesurfer.js~PluginClass#init",
    "method"
  ],
  [
    "src/wavesurfer.js~plugindefinition",
    "typedef/index.html#static-typedef-PluginDefinition",
    "src/wavesurfer.js~PluginDefinition",
    "typedef"
  ],
  [
    "src/wavesurfer.js~wavesurfer#[plugin.name]",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-member-[plugin.name]",
    "src/wavesurfer.js~WaveSurfer#[plugin.name]",
    "member"
  ],
  [
    "src/wavesurfer.js~wavesurfer#[pluginstaticprop]",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-member-[pluginStaticProp]",
    "src/wavesurfer.js~WaveSurfer#[pluginStaticProp]",
    "member"
  ],
  [
    "src/wavesurfer.js~wavesurfer#addplugin",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-addPlugin",
    "src/wavesurfer.js~WaveSurfer#addPlugin",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#cancelajax",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-cancelAjax",
    "src/wavesurfer.js~WaveSurfer#cancelAjax",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#constructor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-constructor-constructor",
    "src/wavesurfer.js~WaveSurfer#constructor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#destroy",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-destroy",
    "src/wavesurfer.js~WaveSurfer#destroy",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#destroyplugin",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-destroyPlugin",
    "src/wavesurfer.js~WaveSurfer#destroyPlugin",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#empty",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-empty",
    "src/wavesurfer.js~WaveSurfer#empty",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#exportimage",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-exportImage",
    "src/wavesurfer.js~WaveSurfer#exportImage",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#exportpcm",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-exportPCM",
    "src/wavesurfer.js~WaveSurfer#exportPCM",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getactiveplugins",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getActivePlugins",
    "src/wavesurfer.js~WaveSurfer#getActivePlugins",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getbackgroundcolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getBackgroundColor",
    "src/wavesurfer.js~WaveSurfer#getBackgroundColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getcurrenttime",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getCurrentTime",
    "src/wavesurfer.js~WaveSurfer#getCurrentTime",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getcursorcolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getCursorColor",
    "src/wavesurfer.js~WaveSurfer#getCursorColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getduration",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getDuration",
    "src/wavesurfer.js~WaveSurfer#getDuration",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getfilters",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getFilters",
    "src/wavesurfer.js~WaveSurfer#getFilters",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getheight",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getHeight",
    "src/wavesurfer.js~WaveSurfer#getHeight",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getmute",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getMute",
    "src/wavesurfer.js~WaveSurfer#getMute",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getplaybackrate",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getPlaybackRate",
    "src/wavesurfer.js~WaveSurfer#getPlaybackRate",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getprogresscolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getProgressColor",
    "src/wavesurfer.js~WaveSurfer#getProgressColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getvolume",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getVolume",
    "src/wavesurfer.js~WaveSurfer#getVolume",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#getwavecolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-getWaveColor",
    "src/wavesurfer.js~WaveSurfer#getWaveColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#init",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-init",
    "src/wavesurfer.js~WaveSurfer#init",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#initplugin",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-initPlugin",
    "src/wavesurfer.js~WaveSurfer#initPlugin",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#isplaying",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-isPlaying",
    "src/wavesurfer.js~WaveSurfer#isPlaying",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#isready",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-member-isReady",
    "src/wavesurfer.js~WaveSurfer#isReady",
    "member"
  ],
  [
    "src/wavesurfer.js~wavesurfer#load",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-load",
    "src/wavesurfer.js~WaveSurfer#load",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#loadblob",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-loadBlob",
    "src/wavesurfer.js~WaveSurfer#loadBlob",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#pause",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-pause",
    "src/wavesurfer.js~WaveSurfer#pause",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#play",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-play",
    "src/wavesurfer.js~WaveSurfer#play",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#playpause",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-playPause",
    "src/wavesurfer.js~WaveSurfer#playPause",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#registerplugins",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-registerPlugins",
    "src/wavesurfer.js~WaveSurfer#registerPlugins",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#seekandcenter",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-seekAndCenter",
    "src/wavesurfer.js~WaveSurfer#seekAndCenter",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#seekto",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-seekTo",
    "src/wavesurfer.js~WaveSurfer#seekTo",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setbackgroundcolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setBackgroundColor",
    "src/wavesurfer.js~WaveSurfer#setBackgroundColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setcurrenttime",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setCurrentTime",
    "src/wavesurfer.js~WaveSurfer#setCurrentTime",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setcursorcolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setCursorColor",
    "src/wavesurfer.js~WaveSurfer#setCursorColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setheight",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setHeight",
    "src/wavesurfer.js~WaveSurfer#setHeight",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setmute",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setMute",
    "src/wavesurfer.js~WaveSurfer#setMute",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setplaybackrate",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setPlaybackRate",
    "src/wavesurfer.js~WaveSurfer#setPlaybackRate",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setprogresscolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setProgressColor",
    "src/wavesurfer.js~WaveSurfer#setProgressColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setsinkid",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setSinkId",
    "src/wavesurfer.js~WaveSurfer#setSinkId",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setvolume",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setVolume",
    "src/wavesurfer.js~WaveSurfer#setVolume",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#setwavecolor",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-setWaveColor",
    "src/wavesurfer.js~WaveSurfer#setWaveColor",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#skip",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-skip",
    "src/wavesurfer.js~WaveSurfer#skip",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#skipbackward",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-skipBackward",
    "src/wavesurfer.js~WaveSurfer#skipBackward",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#skipforward",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-skipForward",
    "src/wavesurfer.js~WaveSurfer#skipForward",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#stop",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-stop",
    "src/wavesurfer.js~WaveSurfer#stop",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#toggleinteraction",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-toggleInteraction",
    "src/wavesurfer.js~WaveSurfer#toggleInteraction",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#togglemute",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-toggleMute",
    "src/wavesurfer.js~WaveSurfer#toggleMute",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#togglescroll",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-toggleScroll",
    "src/wavesurfer.js~WaveSurfer#toggleScroll",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer#util",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-member-util",
    "src/wavesurfer.js~WaveSurfer#util",
    "member"
  ],
  [
    "src/wavesurfer.js~wavesurfer#zoom",
    "class/src/wavesurfer.js~WaveSurfer.html#instance-method-zoom",
    "src/wavesurfer.js~WaveSurfer#zoom",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer.version",
    "class/src/wavesurfer.js~WaveSurfer.html#static-member-VERSION",
    "src/wavesurfer.js~WaveSurfer.VERSION",
    "member"
  ],
  [
    "src/wavesurfer.js~wavesurfer.create",
    "class/src/wavesurfer.js~WaveSurfer.html#static-method-create",
    "src/wavesurfer.js~WaveSurfer.create",
    "method"
  ],
  [
    "src/wavesurfer.js~wavesurfer.util",
    "class/src/wavesurfer.js~WaveSurfer.html#static-member-util",
    "src/wavesurfer.js~WaveSurfer.util",
    "member"
  ],
  [
    "src/wavesurfer.js~wavesurferparams",
    "typedef/index.html#static-typedef-WavesurferParams",
    "src/wavesurfer.js~WavesurferParams",
    "typedef"
  ],
  [
    "src/webaudio.js",
    "file/src/webaudio.js.html",
    "src/webaudio.js",
    "file"
  ],
  [
    "src/webaudio.js~webaudio#constructor",
    "class/src/webaudio.js~WebAudio.html#instance-constructor-constructor",
    "src/webaudio.js~WebAudio#constructor",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#destroy",
    "class/src/webaudio.js~WebAudio.html#instance-method-destroy",
    "src/webaudio.js~WebAudio#destroy",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getaudiocontext",
    "class/src/webaudio.js~WebAudio.html#instance-method-getAudioContext",
    "src/webaudio.js~WebAudio#getAudioContext",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getcurrenttime",
    "class/src/webaudio.js~WebAudio.html#instance-method-getCurrentTime",
    "src/webaudio.js~WebAudio#getCurrentTime",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getduration",
    "class/src/webaudio.js~WebAudio.html#instance-method-getDuration",
    "src/webaudio.js~WebAudio#getDuration",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getofflineaudiocontext",
    "class/src/webaudio.js~WebAudio.html#instance-method-getOfflineAudioContext",
    "src/webaudio.js~WebAudio#getOfflineAudioContext",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getpeaks",
    "class/src/webaudio.js~WebAudio.html#instance-method-getPeaks",
    "src/webaudio.js~WebAudio#getPeaks",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getplaybackrate",
    "class/src/webaudio.js~WebAudio.html#instance-method-getPlaybackRate",
    "src/webaudio.js~WebAudio#getPlaybackRate",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getplayedpercents",
    "class/src/webaudio.js~WebAudio.html#instance-method-getPlayedPercents",
    "src/webaudio.js~WebAudio#getPlayedPercents",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getplayedtime",
    "class/src/webaudio.js~WebAudio.html#instance-method-getPlayedTime",
    "src/webaudio.js~WebAudio#getPlayedTime",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#getvolume",
    "class/src/webaudio.js~WebAudio.html#instance-method-getVolume",
    "src/webaudio.js~WebAudio#getVolume",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#init",
    "class/src/webaudio.js~WebAudio.html#instance-method-init",
    "src/webaudio.js~WebAudio#init",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#ispaused",
    "class/src/webaudio.js~WebAudio.html#instance-method-isPaused",
    "src/webaudio.js~WebAudio#isPaused",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#load",
    "class/src/webaudio.js~WebAudio.html#instance-method-load",
    "src/webaudio.js~WebAudio#load",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#pause",
    "class/src/webaudio.js~WebAudio.html#instance-method-pause",
    "src/webaudio.js~WebAudio#pause",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#play",
    "class/src/webaudio.js~WebAudio.html#instance-method-play",
    "src/webaudio.js~WebAudio#play",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#seekto",
    "class/src/webaudio.js~WebAudio.html#instance-method-seekTo",
    "src/webaudio.js~WebAudio#seekTo",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setfilter",
    "class/src/webaudio.js~WebAudio.html#instance-method-setFilter",
    "src/webaudio.js~WebAudio#setFilter",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setfilters",
    "class/src/webaudio.js~WebAudio.html#instance-method-setFilters",
    "src/webaudio.js~WebAudio#setFilters",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setlength",
    "class/src/webaudio.js~WebAudio.html#instance-method-setLength",
    "src/webaudio.js~WebAudio#setLength",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setpeaks",
    "class/src/webaudio.js~WebAudio.html#instance-method-setPeaks",
    "src/webaudio.js~WebAudio#setPeaks",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setplaybackrate",
    "class/src/webaudio.js~WebAudio.html#instance-method-setPlaybackRate",
    "src/webaudio.js~WebAudio#setPlaybackRate",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setsinkid",
    "class/src/webaudio.js~WebAudio.html#instance-method-setSinkId",
    "src/webaudio.js~WebAudio#setSinkId",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#setvolume",
    "class/src/webaudio.js~WebAudio.html#instance-method-setVolume",
    "src/webaudio.js~WebAudio#setVolume",
    "method"
  ],
  [
    "src/webaudio.js~webaudio#supportswebaudio",
    "class/src/webaudio.js~WebAudio.html#instance-method-supportsWebAudio",
    "src/webaudio.js~WebAudio#supportsWebAudio",
    "method"
  ]
]