name: Release

on:
  push:
    branches:
      - production

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          OLD_VERSION=$(npm show wavesurfer.js version)
          NEW_VERSION=$(node -p 'require("./package.json").version')
          if [ $NEW_VERSION != $OLD_VERSION ]; then
            echo "New version $NEW_VERSION detected"
            echo "::set-output name=version::$NEW_VERSION"
            git log "$OLD_VERSION"..HEAD --pretty=format:"* %s" > TEMP_CHANGELOG.md
          else
            echo "Version $OLD_VERSION hasn't changed, skipping the release"
            exit 1
          fi

      - name: Create a git tag
        if: success()
        run: git tag $NEW_VERSION && git push --tags
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}

      - name: GitHub release
        if: success()
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: TEMP_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: npm publish
